---
- name: to delete the old log files
  hosts: nwsyslog.cn.ibm.com
  user: anstadm
  become: yes
  become_method: sudo
  tasks:
- name: deleting the old log files
  find:
   paths: /log/today
   patterns: '*.log'
   age: '180d'
   file_type: file
  register: filesolderthan180d
- name: clear the logs
  file:
   path: "{{ item path }}"
   state: absent
  with_items: "{{ filesolderthan180d.files }}"
